version: "3"

services:

    app:
        build: ./app
        restart: always
        ports:
            - "8080:3000"
        volumes:
            - ./app/app:/app
        environment:
            NODE_ENV: "development"
            CHOKIDAR_USEPOLLING: "true"

    landing:
        image: nginx
        volumes:
            - ./landing:/usr/share/nginx/html
        ports:
            - "80:80"
        environment:
            - NGINX_HOST=deafboard.com
            - NGINX_PORT=80
