version: "3"

services:

    app:
        build: ./app
        restart: always
        ports:
            - "8080:3000"
        volumes:
            - ./app/app:/app
        environment:
            NODE_ENV: "development"
            CHOKIDAR_USEPOLLING: "true"
